# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fileTransfer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fileTransfer.proto',
  package='FileSend',
  syntax='proto3',
  serialized_options=_b('P\001\242\002\003HLW'),
  serialized_pb=_b('\n\x12\x66ileTransfer.proto\x12\x08\x46ileSend\"\x16\n\x05\x43hunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\t\"\x1e\n\rChuckReceived\x12\r\n\x05reply\x18\x01 \x01(\x05\x32\x45\n\x08\x46ileSend\x12\x39\n\tSendChunk\x12\x0f.FileSend.Chunk\x1a\x17.FileSend.ChuckReceived\"\x00(\x01\x42\x08P\x01\xa2\x02\x03HLWb\x06proto3')
)




_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='FileSend.Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunk', full_name='FileSend.Chunk.chunk', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=54,
)


_CHUCKRECEIVED = _descriptor.Descriptor(
  name='ChuckReceived',
  full_name='FileSend.ChuckReceived',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='FileSend.ChuckReceived.reply', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK
DESCRIPTOR.message_types_by_name['ChuckReceived'] = _CHUCKRECEIVED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), dict(
  DESCRIPTOR = _CHUNK,
  __module__ = 'fileTransfer_pb2'
  # @@protoc_insertion_point(class_scope:FileSend.Chunk)
  ))
_sym_db.RegisterMessage(Chunk)

ChuckReceived = _reflection.GeneratedProtocolMessageType('ChuckReceived', (_message.Message,), dict(
  DESCRIPTOR = _CHUCKRECEIVED,
  __module__ = 'fileTransfer_pb2'
  # @@protoc_insertion_point(class_scope:FileSend.ChuckReceived)
  ))
_sym_db.RegisterMessage(ChuckReceived)


DESCRIPTOR._options = None

_FILESEND = _descriptor.ServiceDescriptor(
  name='FileSend',
  full_name='FileSend.FileSend',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=88,
  serialized_end=157,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendChunk',
    full_name='FileSend.FileSend.SendChunk',
    index=0,
    containing_service=None,
    input_type=_CHUNK,
    output_type=_CHUCKRECEIVED,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILESEND)

DESCRIPTOR.services_by_name['FileSend'] = _FILESEND

# @@protoc_insertion_point(module_scope)
