# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import fileTransfer_pb2 as fileTransfer__pb2


class FileSendStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendChunk = channel.stream_unary(
        '/FileSend.FileSend/SendChunk',
        request_serializer=fileTransfer__pb2.Chunk.SerializeToString,
        response_deserializer=fileTransfer__pb2.ChuckReceived.FromString,
        )


class FileSendServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendChunk(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FileSendServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendChunk': grpc.stream_unary_rpc_method_handler(
          servicer.SendChunk,
          request_deserializer=fileTransfer__pb2.Chunk.FromString,
          response_serializer=fileTransfer__pb2.ChuckReceived.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FileSend.FileSend', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
